## Basic Numpy Array

#### Note: if you know how to use "list" you will know how to use "numpy array" 

In [21]:
import numpy as np

In [22]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([0, .5, 1, 1.5, 2])

In [24]:
a[0], a[1]

(1, 2)

In [25]:
a[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a[1:3]

array([2, 3])

In [27]:
a[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[::2]

array([1, 3, 5, 7, 9])

In [29]:
c = b[0], b[2], b[-1]
c

(0.0, 1.0, 2.0)

In [30]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a.dtype

dtype('int32')

In [33]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [34]:
b.dtype

dtype('float64')

In [35]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [36]:
c = np.array(['a', 'b', 'c'])

In [37]:
c.dtype

dtype('<U1')

## Dimension and shapes

In [38]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [40]:
A.shape

(2, 3)

In [41]:
A.ndim

2

In [42]:
A.size

6

In [44]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]

    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])


In [45]:
B.shape

(2, 2, 3)

In [47]:
B.size

12

In [48]:
B.ndim

3

In [50]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]

    ],
    [
        [6, 5, 4],
    ]
])


C:\Users\omarr\AppData\Local\Temp\ipykernel_19500\136423123.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [52]:
C.dtype

dtype('O')

In [53]:
C.shape

(2,)

In [54]:
C.size

2

## Indexing and Slicing Matrix 

12