In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('./datasets/feature_data.csv')
df

First Name Last Name   Age   Salary  Region Purchased
0       Ahmed    Radwan  35.0   3000.0    Asia        No
1     Mustafa    Othman  34.0  12000.0  Africa       Yes
2       Omnia    Nasser  28.0   7000.0  Africa        No
3      Saddik    Burhan  45.0   8500.0  Europe        No
4     Mustafa     Jalil  38.0  45000.0  Africa       Yes
5      Hesham     Naser   NaN      NaN    Asia       Yes
6  Abulrahman       NaN  26.0   6700.0    Asia        No
7     Mohamed      Ouda  33.0  10500.0    Asia       Yes
8      Mariam     Mazen  18.0      NaN  Africa        No

In [3]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()

In [5]:
df['Salary']

0     3000.0
1    12000.0
2     7000.0
3     8500.0
4    45000.0
5        NaN
6     6700.0
7    10500.0
8        NaN
Name: Salary, dtype: float64

In [8]:
sc.fit(df[['Salary']])

MinMaxScaler()

In [11]:
sc.transform(df[['Salary']])

array([[0.        ],
       [0.21428571],
       [0.0952381 ],
       [0.13095238],
       [1.        ],
       [       nan],
       [0.08809524],
       [0.17857143],
       [       nan]])

In [17]:
sc.fit_transform(df[['Salary']])


array([[0.        ],
       [0.21428571],
       [0.0952381 ],
       [0.13095238],
       [1.        ],
       [       nan],
       [0.08809524],
       [0.17857143],
       [       nan]])

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
sc = StandardScaler()

In [22]:
sc.fit_transform(df[['Salary']])

array([[-0.77372619],
       [-0.09388309],
       [-0.4715737 ],
       [-0.35826652],
       [ 2.39887492],
       [        nan],
       [-0.49423514],
       [-0.20719028],
       [        nan]])

In [23]:
from sklearn.preprocessing import LabelEncoder

In [25]:
df

First Name Last Name   Age   Salary  Region Purchased
0       Ahmed    Radwan  35.0   3000.0    Asia        No
1     Mustafa    Othman  34.0  12000.0  Africa       Yes
2       Omnia    Nasser  28.0   7000.0  Africa        No
3      Saddik    Burhan  45.0   8500.0  Europe        No
4     Mustafa     Jalil  38.0  45000.0  Africa       Yes
5      Hesham     Naser   NaN      NaN    Asia       Yes
6  Abulrahman       NaN  26.0   6700.0    Asia        No
7     Mohamed      Ouda  33.0  10500.0    Asia       Yes
8      Mariam     Mazen  18.0      NaN  Africa        No

In [28]:
enc = LabelEncoder()

In [29]:
enc.fit_transform(df[['Region']])

c:\Users\omarr\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 0, 2, 0, 1, 1, 1, 0])

In [30]:
enc.fit_transform(df[['Purchased']])


c:\Users\omarr\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, 0, 1, 1, 0, 1, 0])

In [31]:
from sklearn.preprocessing import OneHotEncoder 

In [32]:
enc = OneHotEncoder()

In [33]:
df

First Name Last Name   Age   Salary  Region Purchased
0       Ahmed    Radwan  35.0   3000.0    Asia        No
1     Mustafa    Othman  34.0  12000.0  Africa       Yes
2       Omnia    Nasser  28.0   7000.0  Africa        No
3      Saddik    Burhan  45.0   8500.0  Europe        No
4     Mustafa     Jalil  38.0  45000.0  Africa       Yes
5      Hesham     Naser   NaN      NaN    Asia       Yes
6  Abulrahman       NaN  26.0   6700.0    Asia        No
7     Mohamed      Ouda  33.0  10500.0    Asia       Yes
8      Mariam     Mazen  18.0      NaN  Africa        No

In [35]:
enc.fit_transform(df[['Region']]).toarray()

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [36]:
pd.get_dummies(df['Region'])

Africa  Asia  Europe
0       0     1       0
1       1     0       0
2       1     0       0
3       0     0       1
4       1     0       0
5       0     1       0
6       0     1       0
7       0     1       0
8       1     0       0

In [38]:
pd.get_dummies(df['Purchased'],drop_first=True)


Yes
0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0